name: Deploy Jekyll + React to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1'
          cache: 'npm'
          # Removed cache-dependency-path since package-lock.json is at repo root

      - name: Install React dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Copy React build into Jekyll site
        run: |
          rm -rf public/react
          mkdir -p public/react
          cp -r build/* public/react/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.publish.outputs.page_url }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        id: publish
        uses: bitovi/github-actions-react-to-github-pages@v1.2.4
        with:
          path: ./_site
